In [1]:
import pandas as pd

In [2]:
url="https://en.wikipedia.org/wiki/Lionel_Messi"

In [3]:
table=pd.read_html(url)
len(table)

65

In [6]:
matching_tables=pd.read_html(url,match='Goals')
len(matching_tables)

2

In [9]:
matching_tables[0]

,0,1,2,3,4,5,6,7,8,9,10,11
0,Club,Season,League,Copa del Rey,Champions League,Other,Total,NaN,NaN,NaN,NaN,NaN
1,Division,Apps,Goals,Apps,Goals,Apps,Goals,Apps,Goals,Apps,Goals,NaN
2,Barcelona C,2003–04[496],Tercera División,10,5,—,—,—,10,5,NaN,NaN
3,Barcelona B,2003–04[39],Segunda División B,5,0,—,—,—,5,0,NaN,NaN
4,2004–05[40],Segunda División B,17,6,—,—,—,17,6,NaN,NaN,NaN
5,Total,22,6,—,—,—,22,6,NaN,NaN,NaN,NaN
6,Barcelona,2004–05[40],La Liga,7,1,1,0,1,0,—,9,1.0
7,2005–06[54],La Liga,17,6,2,1,6,1,0,0,25,8.0
8,2006–07[57],La Liga,26,14,2,2,5,1,3[a],0,36,17.0
9,2007–08[72],La Liga,28,10,3,0,9,6,—,40,16,NaN
10,2008–09[80],La Liga,31,23,8,6,12,9,—,51,38,NaN
11,2009–10[93],La Liga,35,34,3,1,11,8,4[b],4,53,47.0
12,2010–11[109],La Liga,33,31,7,7,13,12,2[c],3,55,53.0
13,2011–12[114],La Liga,37,50,7,3,11,14,5[d],6,60,73.0
14,2012–13[153],La Liga,32,46,5,4,11,8,2[c],2,50,60.0
15,2013–14[160],La Liga,31,28,6,5,7,8,2[c],0,46,41.0
16,2014–15[497],La Liga,38,43,6,5,13,10,—,57,58,NaN
17,2015–16[498],La Liga,33,26,5,5,7,6,4[e],4,49,41.0
18,2016–17[499],La Liga,34,37,7,5,9,11,2[c],1,52,54.0
19,2017–18[500],La Liga,36,34,6,4,10,6,2[c],1,54,45.0
20,2018–19[501],La Liga,34,36,5,3,10,12,1[c],0,50,51.0
21,2019–20[502],La Liga,2,0,0,0,2,0,0[c],0,4,0.0
22,Total,454,419,73,51,137,112,27,21,691,603,NaN
23,Career total,486,430,73,51,137,112,27,21,723,614,NaN